spring:
  application:
    name: modulo6_desafio

  datasource:
    url: jdbc:postgresql://localhost:5432/teach_db
    username: postgres
    password: root

  jpa:
    hibernate:
    ddl-auto: validate
    show-sql: true
    open-in-view: false